services:
- type: web
  runtime: python
  name: vaccination-app
  buildCommand: ./build.sh
  startCommand: cd mysite && gunicorn mysite.wsgi:application
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: vaccination-db
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  - key: DJANGO_ALLOWED_HOSTS
    value: .onrender.com
  - key: DEBUG
    value: "false"

databases:
- name: vaccination-db
  databaseName: vaccination
  user: vaccination
